#!/usr/bin/env bash
# =============================================================================
# REDI Phase 5 — Configure Authentik identity baseline, MFA, GitLab OIDC
# Run on redi-mjk-01 only. Idempotent where possible.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REDI_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"
require_root

[[ "$(hostname -s)" == "redi-mjk-01" ]] || { log_error "Run on redi-mjk-01"; exit 1; }

ENV_FILE="${REDI_ROOT}/compose/authentik/.env"
# shellcheck source=/dev/null
source "${ENV_FILE}"

OIDC_ENV="${REDI_ROOT}/compose/gitlab/.env.oidc"
mkdir -p "$(dirname "${OIDC_ENV}")"

log_info "Applying REDI identity baseline via Authentik shell"

PY="${SCRIPT_DIR}/configure-authentik-identity.py"
docker cp "${PY}" redi-authentik-server:/tmp/configure_identity.py
OUT="$(docker exec redi-authentik-server ak shell -c "exec(open('/tmp/configure_identity.py').read())" 2>&1 | grep -E '^(group_ok|admin_|flow_ok|policy_ok|provider_ok|app_ok|user_ok|OIDC_)' || true)"
echo "${OUT}"

OIDC_CLIENT_ID="$(echo "${OUT}" | sed -n 's/^OIDC_CLIENT_ID=//p')"
OIDC_CLIENT_SECRET="$(echo "${OUT}" | sed -n 's/^OIDC_CLIENT_SECRET=//p')"
OIDC_ISSUER="$(echo "${OUT}" | sed -n 's/^OIDC_ISSUER=//p')"
[[ -n "${OIDC_CLIENT_ID}" && -n "${OIDC_CLIENT_SECRET}" ]] || {
  docker exec redi-authentik-server ak shell -c "
from authentik.providers.oauth2.models import OAuth2Provider
p = OAuth2Provider.objects.get(name='REDI GitLab')
print(p.client_id)
print(p.client_secret)
" 2>/dev/null | tail -2 | {
    read -r OIDC_CLIENT_ID
    read -r OIDC_CLIENT_SECRET
  }
  OIDC_ISSUER="https://auth.letsredi.com/application/o/gitlab/"
}

cat > "${OIDC_ENV}" <<EOF
# Generated by configure-authentik-identity.sh — do not commit
GITLAB_OIDC_ENABLED=true
GITLAB_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
GITLAB_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
GITLAB_OIDC_ISSUER=${OIDC_ISSUER}
EOF
chmod 600 "${OIDC_ENV}"

log_info "Identity baseline configured. OIDC env: ${OIDC_ENV}"
