# =============================================================================
# REDI — Traefik: Authentik on redi-mjk-01
# =============================================================================

http:
  serversTransports:
    authentik-transport:
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 120s

  routers:
    authentik:
      rule: "Host(`auth.letsredi.com`)"
      entryPoints:
        - websecure
      service: authentik
      middlewares:
        - security-headers@file
        - rate-limit@file
      tls:
        certResolver: letsencrypt-http

    authentik-http:
      rule: "Host(`auth.letsredi.com`)"
      entryPoints:
        - web
      service: authentik
      middlewares:
        - security-headers@file

  services:
    authentik:
      loadBalancer:
        sticky:
          cookie:
            name: _authentik_session_sticky
        servers:
          - url: "http://100.81.86.37:9100" # MJK
          - url: "http://100.79.82.92:9100" # JKT
          - url: "http://100.67.138.25:9100" # SBY
        serversTransport: authentik-transport
        healthCheck:
          path: /-/health/ready/
          interval: 15s
          timeout: 3s
